### server
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

druid:
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shiro_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 5000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select 1
      test-on-return: false
      min-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 600000
      filters: config

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.management.warehouse.core.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      id-type: auto
      field-strategy: ignored
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
