server:
  port: 8989


# Redis
spring:
  redis:
    database: 0
    timeout: 5000
    # Redis服务器地址
    host: 127.0.0.1
    #host: 47.110.125.189
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: xiqiuwei
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
