server:
  port: 8890
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: redis-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 10000
        min-idle: 0