server:
  port: 8895
druid:
  spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/shiro_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 5000
      test-on-borrow: true
      test-while-idle: true
      validation-query: select
      test-on-return: false
      min-evictable-idle-time-millis: 1800000
      time-between-eviction-runs-millis: 600000
      filters: config
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.management.shiro.demo.dataobject
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_null
      #驼峰下划线转换
      column-like: true
      table-underline: true
      #数据库大写下划线转换
      capital-mode: true
    #db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
#    logic-delete-value: 0
#    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
