server:
  port: 80

spring:
  application:
    name: zuul_server

eureka:
  client:
    # 集群的三个节点
    service-url:
      defaultZone: http://eureka1.xiqiuwei.com:10010/eureka,http://eureka2.xiqiuwei.com:10011/eureka,http://eureka3.xiqiuwei.com:10012/eureka
zuul:
 # prefix: /api # 全局前缀
 # retryable: true
  routes:
    hello_world: /hello/** # 将微服务模块映射到/hello/**下面
    advice_server: /advice/**
    auth_center: /auth/** # 鉴权中心
  ignored-services: "*" # 忽略所有的服务
  add-host-header: true # 此处解决后端服务重定向导致用户浏览的host变成 后端服务的host的问题
  # 不忽略任何头部信息，所有header都转发到下游的资源服务器
  sensitive-headers: # 接收header信息


# 白名单
whitelist:
  allowPaths:
    - /auth


